namespace FleetManagementSystem.Tests;

public class AcceptanceMatrixTests
{
    [Fact]
    public async Task ReportingAndAlertAcceptanceMatrix_OneHundredEightyThreeChecks_Pass()
    {
        await using var harness = await AcceptanceHarness.CreateAsync();
        var seed = await SeedBusinessDataAsync(harness);
        var checks = new List<AcceptanceCheck>();

        var expectations = BuildReportExpectations();
        foreach (var expectation in expectations)
        {
            checks.Add(new($"{expectation.Type} title", async () =>
            {
                var report = await harness.ReportingService.GenerateReportAsync(new ReportFilterDto { ReportType = expectation.Type });
                Assert.Equal(expectation.Title, report.ReportTitle);
            }));

            checks.Add(new($"{expectation.Type} generated by system", async () =>
            {
                var report = await harness.ReportingService.GenerateReportAsync(new ReportFilterDto { ReportType = expectation.Type });
                Assert.Equal("System", report.GeneratedBy);
            }));

            checks.Add(new($"{expectation.Type} generated date", async () =>
            {
                var before = DateTime.UtcNow.AddSeconds(-5);
                var report = await harness.ReportingService.GenerateReportAsync(new ReportFilterDto { ReportType = expectation.Type });
                Assert.True(report.GeneratedDate >= before);
            }));

            checks.Add(new($"{expectation.Type} data list", async () =>
            {
                var report = await harness.ReportingService.GenerateReportAsync(new ReportFilterDto { ReportType = expectation.Type });
                Assert.NotNull(report.Data);
            }));

            checks.Add(new($"{expectation.Type} future filter", async () =>
            {
                var report = await harness.ReportingService.GenerateReportAsync(new ReportFilterDto
                {
                    ReportType = expectation.Type,
                    StartDate = DateTime.Today.AddYears(20),
                    EndDate = DateTime.Today.AddYears(20).AddDays(1)
                });

                Assert.Empty(report.Data);
            }));

            checks.Add(new($"{expectation.Type} invalid range rejected", async () =>
            {
                await Assert.ThrowsAsync<InvalidOperationException>(() => harness.ReportingService.GenerateReportAsync(new ReportFilterDto
                {
                    ReportType = expectation.Type,
                    StartDate = DateTime.Today,
                    EndDate = DateTime.Today.AddDays(-1)
                }));
            }));

            foreach (var column in expectation.Columns)
            {
                checks.Add(new($"{expectation.Type} column {column}", async () =>
                {
                    var report = await harness.ReportingService.GenerateReportAsync(new ReportFilterDto { ReportType = expectation.Type });
                    Assert.Contains(column, report.Columns);
                }));
            }
        }

        checks.AddRange(BuildDataChecks(harness, seed));

        Assert.Equal(160, checks.Count);

        for (var index = 0; index < checks.Count; index++)
        {
            try
            {
                await checks[index].Execute();
            }
            catch (Exception ex)
            {
                throw new InvalidOperationException($"Acceptance check {index + 1:000} failed: {checks[index].Name}", ex);
            }
        }
    }

    private static IReadOnlyList<ReportExpectation> BuildReportExpectations() =>
        new List<ReportExpectation>
        {
            new("vehicles", "تقرير المركبات", new[] { "رقم السيارة", "الموديل", "سنة الصنع", "رقم الشاسيه", "رقم الموتور", "نهاية الترخيص", "شركة التأمين", "نهاية التأمين", "تغيير الزيت كل كام كم" }),
            new("vehicletrips", "تقرير تشغيلات العربية ACC-001", new[] { "سيريال", "التاريخ", "النهاية", "رقم السيارة", "من", "إلى", "السائق", "الموصي", "المشرف", "الغرض", "الحالة", "المسافة", "ملاحظات" }),
            new("alltrips", "تقرير جميع التشغيلات", new[] { "سيريال", "التاريخ", "النهاية", "رقم السيارة", "من", "إلى", "السائق", "الموصي", "المشرف", "الغرض", "الحالة", "المسافة", "ملاحظات" }),
            new("vehiclelicenses", "تقرير تراخيص العربيات", new[] { "رقم السيارة", "الموديل", "سنة الصنع", "رقم الشاسيه", "رقم الموتور", "بداية الترخيص", "نهاية الترخيص", "الحالة", "الإنذار" }),
            new("insurance", "تقرير التأمينات", new[] { "رقم السيارة", "الموديل", "سنة الصنع", "رقم الشاسيه", "رقم الموتور", "رقم الوثيقة", "شركة التأمين", "نوع الوثيقة", "بداية التأمين", "نهاية التأمين", "القسط", "الحالة", "الإنذار" }),
            new("contracts", "تقرير العقود", new[] { "رقم العقد", "رقم السيارة", "العميل", "بداية العقد", "نهاية العقد", "قيمة العقد", "المدفوع" }),
            new("maintenance", "تقرير الصيانة", new[] { "رقم السيارة", "نوع الصيانة", "تاريخ الطلب", "الحالة", "التكلفة الفعلية" }),
            new("oilchanges", "تقرير الزيوت", new[] { "رقم السيارة", "التاريخ", "نوع السجل", "عملية التغيير", "عداد التغيير", "قراءة العداد", "نوع الزيت", "كمية الزيت باللتر", "تكلفة الزيت", "تغيير الزيت كل كام كم", "المقطوع منذ آخر تغيير", "تغيير الزيت القادم", "المتبقي كم", "الإنذار", "الحالة" }),
            new("treasury", "تقرير الخزينة", new[] { "التاريخ", "نوع الحركة", "المبلغ", "الوصف", "مرتبط بـ" })
        };

    private static IReadOnlyList<AcceptanceCheck> BuildDataChecks(AcceptanceHarness harness, SeedData seed) =>
        new List<AcceptanceCheck>
        {
            new("vehicles report contains seeded vehicle", async () => Assert.Contains(await Rows(harness, "vehicles"), r => Text(r, "رقم السيارة") == seed.Vehicle.PlateNumber)),
            new("all trips has data", async () => Assert.NotEmpty(await Rows(harness, "alltrips"))),
            new("all trips contains start location", async () => Assert.Contains(await Rows(harness, "alltrips"), r => Text(r, "من") == "المقر")),
            new("all trips contains end location", async () => Assert.Contains(await Rows(harness, "alltrips"), r => Text(r, "إلى").Contains("العميل", StringComparison.Ordinal))),
            new("all trips distance", async () => Assert.Contains(await Rows(harness, "alltrips"), r => Number(r, "المسافة") == 300m)),
            new("vehicle trips respects vehicle filter", async () => Assert.All(await Rows(harness, "vehicletrips", seed.Vehicle.Id), r => Assert.Equal(seed.Vehicle.PlateNumber, Text(r, "رقم السيارة")))),
            new("oil report next odometer", async () => Assert.Contains(await Rows(harness, "oilchanges"), r => Number(r, "تغيير الزيت القادم") == 9800m)),
            new("oil report current odometer", async () => Assert.Contains(await Rows(harness, "oilchanges"), r => Number(r, "قراءة العداد") == 9600m)),
            new("oil report remaining km", async () => Assert.Contains(await Rows(harness, "oilchanges"), r => Number(r, "المتبقي كم") == 200m)),
            new("oil report due alert", async () => Assert.Contains(await Rows(harness, "oilchanges"), r => Text(r, "الإنذار").Contains("متبقي 200", StringComparison.Ordinal))),
            new("insurance report policy", async () => Assert.Contains(await Rows(harness, "insurance"), r => Text(r, "رقم الوثيقة") == "INS-ACC-001")),
            new("insurance report 60 day status", async () => Assert.Contains(await Rows(harness, "insurance"), r => Text(r, "الحالة") == "Expiring")),
            new("insurance report 60 day alert", async () => Assert.Contains(await Rows(harness, "insurance"), r => Text(r, "الإنذار").Contains("45", StringComparison.Ordinal))),
            new("vehicle license report expiry alert", async () => Assert.Contains(await Rows(harness, "vehiclelicenses"), r => Text(r, "الإنذار").Contains("20", StringComparison.Ordinal))),
            new("treasury report income display", async () => Assert.Contains(await Rows(harness, "treasury"), r => Text(r, "نوع الحركة") == "إيراد")),
            new("maintenance report cost", async () => Assert.Contains(await Rows(harness, "maintenance"), r => Number(r, "التكلفة الفعلية") == 900m)),
            new("contract report value", async () => Assert.Contains(await Rows(harness, "contracts"), r => Number(r, "قيمة العقد") == 5000m))
        };

    private static async Task<IReadOnlyList<Dictionary<string, object>>> Rows(AcceptanceHarness harness, string reportType, int? vehicleId = null)
    {
        var report = await harness.ReportingService.GenerateReportAsync(new ReportFilterDto
        {
            ReportType = reportType,
            VehicleId = vehicleId
        });

        return report.Data;
    }

    private static async Task<(Dictionary<string, object> Row, string Plate)> FirstVehicleRow(AcceptanceHarness harness, SeedData seed)
    {
        var row = (await Rows(harness, "vehicles")).First(r => Text(r, "رقم السيارة") == seed.Vehicle.PlateNumber);
        return (row, seed.Vehicle.PlateNumber);
    }

    private static string Text(Dictionary<string, object> row, string column) =>
        row.TryGetValue(column, out var value) ? value?.ToString() ?? string.Empty : string.Empty;

    private static decimal Number(Dictionary<string, object> row, string column)
    {
        if (!row.TryGetValue(column, out var value) || value is null)
        {
            return 0;
        }

        return Convert.ToDecimal(value);
    }

    private static async Task<SeedData> SeedBusinessDataAsync(AcceptanceHarness h)
    {
        var vehicle = await h.VehicleService.SaveAsync(new VehicleFormDto
        {
            PlateNumber = "ACC-001",
            VehicleTypeId = h.DefaultVehicleTypeId,
            Model = "Toyota Corolla",
            Year = 2026,
            Manufacturer = "Toyota",
            Color = "أبيض",
            ChassisNumber = "ACC-CH-001",
            EngineNumber = "ACC-EN-001",
            Status = "Available",
            CurrentMileage = 4500,
            PurchaseDate = DateTime.Today.AddMonths(-3),
            RegistrationStartDate = DateTime.Today.AddMonths(-1),
            RegistrationExpiryDate = DateTime.Today.AddDays(20),
            RegistrationType = "ترخيص",
            AccidentInsuranceDetails = "تأمين حوادث",
            OilChangeIntervalKm = 5000,
            MaintenanceIntervalKm = 15000
        });

        var driver = await h.DriverService.SaveAsync(new DriverFormDto
        {
            FullName = "سائق قبول",
            NationalId = "2990101000001",
            PhoneNumber = "01000000000",
            LicenseNumber = "DRV-ACC-001",
            LicenseExpiryDate = DateTime.Today.AddYears(1),
            LicenseType = "خاصة",
            IsActive = true,
            Address = "القاهرة"
        });

        var requester = await h.EmployeeService.SaveAsync(new EmployeeFormDto
        {
            FullName = "طالب قبول",
            EmployeeId = "EMP-ACC-REQ",
            Department = "التشغيل",
            Position = "موصي",
            HireDate = DateTime.Today.AddMonths(-6),
            Status = "Active",
            PhoneNumber = "01000000000"
        });

        var supervisor = await h.EmployeeService.SaveAsync(new EmployeeFormDto
        {
            FullName = "مشرف قبول",
            EmployeeId = "EMP-ACC-SUP",
            Department = "التشغيل",
            Position = "مشرف",
            HireDate = DateTime.Today.AddMonths(-6),
            Status = "Active",
            PhoneNumber = "01000000000"
        });

        await h.InsuranceService.SaveAsync(new InsuranceFormDto
        {
            VehicleId = vehicle.Id,
            PolicyNumber = "INS-ACC-001",
            InsuranceCompany = "شركة قبول",
            PolicyType = "تأمين حوادث",
            StartDate = DateTime.Today.AddMonths(-1),
            ExpiryDate = DateTime.Today.AddDays(45),
            PremiumAmount = 2000,
            CoverageAmount = 100000,
            CoverageDetails = "تغطية قبول",
            AgentName = "مندوب قبول",
            AgentPhoneNumber = "01000000000"
        });

        var trip = await h.TripService.SaveAsync(new TripFormDto
        {
            VehicleId = vehicle.Id,
            DriverId = driver.Id,
            RequesterEmployeeId = requester.Id,
            RequesterNameText = requester.FullName,
            SupervisorEmployeeId = supervisor.Id,
            StartDate = DateTime.Today.AddHours(9),
            EndDate = DateTime.Today.AddHours(12),
            StartLocation = "المقر",
            EndLocation = "العميل - فرع أكتوبر",
            StartMileage = 4500,
            EndMileage = 4800,
            Distance = 300,
            Purpose = "تشغيل قبول",
            Status = "Closed",
            Notes = "بيانات قبول"
        });

        await h.FuelService.SaveAsync(new FuelTransactionFormDto
        {
            VehicleId = vehicle.Id,
            TripId = trip.Id,
            TransactionDate = DateTime.Today,
            FuelType = "بنزين",
            Quantity = 50,
            UnitPrice = 15,
            TotalCost = 750,
            FuelStation = "محطة قبول",
            Odometer = 4800
        });

        await h.OilChangeService.SaveAsync(new OilChangeFormDto
        {
            VehicleId = vehicle.Id,
            ChangeDate = DateTime.Today.AddDays(-10),
            OdometerAtChange = 4800,
            CurrentOdometer = 9600,
            CurrentOdometerDate = DateTime.Today,
            OilType = "10W-40",
            Quantity = 4,
            Cost = 600,
            Status = "Completed"
        });

        var vehicleAfterOil = await h.VehicleService.GetByIdAsync(vehicle.Id) ?? vehicle;
        vehicleAfterOil.CurrentMileage = 9600;
        await h.VehicleService.SaveAsync(new VehicleFormDto
        {
            Id = vehicleAfterOil.Id,
            PlateNumber = vehicleAfterOil.PlateNumber,
            VehicleTypeId = vehicleAfterOil.VehicleTypeId,
            Model = vehicleAfterOil.Model,
            Year = vehicleAfterOil.Year,
            Manufacturer = vehicleAfterOil.Manufacturer,
            Color = vehicleAfterOil.Color,
            ChassisNumber = vehicleAfterOil.ChassisNumber,
            EngineNumber = vehicleAfterOil.EngineNumber,
            Status = vehicleAfterOil.Status,
            CurrentMileage = 9600,
            PurchaseDate = vehicleAfterOil.PurchaseDate,
            RegistrationStartDate = vehicleAfterOil.RegistrationStartDate,
            RegistrationExpiryDate = vehicleAfterOil.RegistrationExpiryDate,
            RegistrationType = vehicleAfterOil.RegistrationType,
            AccidentInsuranceDetails = vehicleAfterOil.AccidentInsuranceDetails,
            OilChangeIntervalKm = vehicleAfterOil.OilChangeIntervalKm,
            MaintenanceIntervalKm = vehicleAfterOil.MaintenanceIntervalKm,
            Notes = vehicleAfterOil.Notes
        });

        await h.ContractService.SaveAsync(new ContractFormDto
        {
            ContractNumber = "CON-ACC-001",
            VehicleId = vehicle.Id,
            ContractStatusId = h.DefaultContractStatusId,
            ClientName = "عميل قبول",
            StartDate = DateTime.Today.AddDays(-5),
            EndDate = DateTime.Today.AddMonths(1),
            ContractValue = 5000,
            PaidAmount = 1000
        });

        await h.MaintenanceService.SaveAsync(new MaintenanceRequestFormDto
        {
            VehicleId = vehicle.Id,
            MaintenanceTypeId = h.DefaultMaintenanceTypeId,
            ServiceProviderId = h.DefaultServiceProviderId,
            RequestDate = DateTime.Today,
            CompletionDate = DateTime.Today,
            Status = "Completed",
            Description = "صيانة قبول",
            EstimatedCost = 1000,
            ActualCost = 900
        });

        await h.TreasuryService.SaveAsync(new TreasuryTransactionFormDto
        {
            TransactionDate = DateTime.Today,
            TransactionType = "Income",
            Amount = 3000,
            Description = "إيراد قبول",
            PaymentMethod = "Cash"
        });

        return new SeedData(vehicle, trip);
    }

    private sealed record AcceptanceCheck(string Name, Func<Task> Execute);

    private sealed record ReportExpectation(string Type, string Title, IReadOnlyList<string> Columns);

    private sealed record SeedData(VehicleDto Vehicle, TripDto Trip);

    private sealed class AcceptanceHarness : IAsyncDisposable
    {
        private readonly SqliteConnection _connection;

        private AcceptanceHarness(SqliteConnection connection, FleetDbContext context)
        {
            _connection = connection;
            Context = context;
            AuditService = new AuditService(context);
            NotificationService = new NotificationService(context);
            VehicleService = new VehicleService(context, AuditService, NotificationService);
            DriverService = new DriverService(context, AuditService);
            EmployeeService = new EmployeeService(context, AuditService);
            TripService = new TripService(context, AuditService);
            FuelService = new FuelService(context, AuditService);
            OilChangeService = new OilChangeService(context, AuditService);
            InsuranceService = new InsuranceService(context, AuditService);
            ContractService = new ContractService(context, AuditService, NotificationService);
            MaintenanceService = new MaintenanceService(context, AuditService, NotificationService);
            TreasuryService = new TreasuryService(context, AuditService);
            ReportingService = new ReportingService(context);
        }

        public FleetDbContext Context { get; }
        public IAuditService AuditService { get; }
        public INotificationService NotificationService { get; }
        public IVehicleService VehicleService { get; }
        public IDriverService DriverService { get; }
        public IEmployeeService EmployeeService { get; }
        public ITripService TripService { get; }
        public IFuelService FuelService { get; }
        public IOilChangeService OilChangeService { get; }
        public IInsuranceService InsuranceService { get; }
        public IContractService ContractService { get; }
        public IMaintenanceService MaintenanceService { get; }
        public ITreasuryService TreasuryService { get; }
        public IReportingService ReportingService { get; }
        public int DefaultVehicleTypeId { get; private init; }
        public int DefaultContractStatusId { get; private init; }
        public int DefaultMaintenanceTypeId { get; private init; }
        public int DefaultServiceProviderId { get; private init; }

        public static async Task<AcceptanceHarness> CreateAsync()
        {
            var connection = new SqliteConnection("Data Source=:memory:");
            await connection.OpenAsync();

            var options = new DbContextOptionsBuilder<FleetDbContext>()
                .UseSqlite(connection)
                .Options;

            var context = new FleetDbContext(options);
            await new DataBootstrapService(context).InitializeAsync();

            return new AcceptanceHarness(connection, context)
            {
                DefaultVehicleTypeId = await context.VehicleTypes.Select(x => x.Id).FirstAsync(),
                DefaultContractStatusId = await context.ContractStatuses.Select(x => x.Id).FirstAsync(),
                DefaultMaintenanceTypeId = await context.MaintenanceTypes.Select(x => x.Id).FirstAsync(),
                DefaultServiceProviderId = await context.ServiceProviders.Select(x => x.Id).FirstAsync()
            };
        }

        public async ValueTask DisposeAsync()
        {
            await Context.DisposeAsync();
            await _connection.DisposeAsync();
        }
    }
}
